// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyjtsaeuxgwylxyaknwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5anRzYWV1eGd3eWx4eWFrbndrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTQ4OTAsImV4cCI6MjA3Mjk5MDg5MH0.ZIo5lvJ4VvNYl8AGNgVugiJfmvyGAYAQ-Ra-sqXKC84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});